### PR TITLE
No longer rely on caller_runs for backpressure in sqs active job executor

### LINKED ISSUE #123: Clean shutdown procedure is not invoked when the main thread participates in thread pool execution
`Concurrent::ThreadPoolExecutor` is [initialized](https://github.com/aws/aws-sdk-rails/blob/3c4e4828715a26154a918a5583e08f4f7adebb73/lib/aws/rails/sqs_active_job/executor.rb#L15) with `fallback_policy: :caller_runs`
This means that the work [will be executed in the thread of the caller](https://ruby-concurrency.github.io/concurrent-ruby/1.1.8/file.thread_pools.html), instead of being given to another thread in the pool when the queue of waiting work has reached the maximum size (**backpressure**) and no new threads can be created.
In such case all the exceptions are [rescued](https://github.com/ruby-concurrency/concurrent-ruby/blob/b5e090b9da95c63cd006721ae6a7e594ec78512b/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb#L361) in the `RubyThreadPoolExecutor#run_task`.
This means that `Aws::Rails::SqsActiveJob::Interrupt#run` [rescue block](https://github.com/aws/aws-sdk-rails/blob/f05437103a51dc52c41a4b349d3499580b83a677/lib/aws/rails/sqs_active_job/poller.rb#L57) is not triggered and clean shutdown procedure is not invoked.

### PR DESCRIPTION
**Pull request by alextwoods**
Changes the `fallback_policy` on the executor to `:abort` instead of using `caller_runs`.  This will raise an `Concurrent::RejectedExecutionError` when posting to the executor when it does not have capacity.  It then uses a [Concurrent:Event](https://ruby-concurrency.github.io/concurrent-ruby/master/Concurrent/Event.html) to block the calling thread until the next task completes.

*Issue #, if available:*
Fixes #123 

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

### CODE REVIEW

File: lib/aws/rails/sqs_active_job/executor.rb [hunk 1]
```diff
@@ -12,18 +12,19 @@ class Executor
...
         }.freeze
 
         def initialize(options = {})
           @executor = Concurrent::ThreadPoolExecutor.new(DEFAULTS.merge(options))
           @retry_standard_errors = options[:retry_standard_errors]
           @logger = options[:logger] || ActiveSupport::Logger.new($stdout)
+          @task_complete = Concurrent::Event.new
         end
 
         def execute(message)
```
Comment (mullermp) [inline lib/aws/rails/sqs_active_job/executor.rb:25]: I think you can use implicit `begin` here but it will require another method. You possibly should refactor this out.

**Review by mullermp — APPROVED** [review]
Needs a test I think.
