### PR TITLE
Check if action mailbox config is defined

### LINKED ISSUE #133: V4 - Usage without ActiveStorage and ActiveMailbox enabled
Hello!

We are using the gem for sending email via SES, but we do not have ActionMailbox or ActiveStorage loaded in the app.
On gem version 4.0.1 we therefore cannot load the app due to the error:

```ruby
Couldn't find Active Storage configuration in /home/runner/work/repo/config/storage.yml
```

Our `application.rb` starts like:

```ruby
require_relative "boot"

require "rails"
# Pick the frameworks you want:
require "active_model/railtie"
require "active_job/railtie"
require "active_record/railtie"
# require "active_storage/engine"
require "action_controller/railtie"
require "action_mailer/railtie"
# require "action_mailbox/engine"
# require "action_text/engine"
require "action_view/railtie"
require "action_cable/engine"
require "sprockets/railtie"
require "rails/test_unit/railtie"
```

Is there no way to use this gem unless you have ActionMailbox and ActiveStorage enabled?

### PR DESCRIPTION
**Pull request by mullermp**
Potentially fixes #133

### CODE REVIEW

**Comment by mullermp** [comment]
@ssunday @bobf Sorry to bother - but do you think this will fix #133? Would this change work in your application?

I think there's something smelly about this as it is currently. I tried using `ActiveSupport.on_load(:action_mailbox)` but to no avail. I also think maybe this engine should not be loaded all the time unless action mailbox is required. Should this also live in a railtie? Let me know what you all think.

**Comment by ssunday** [comment]
@mullermp No idea. This seems like it makes sense, but I don't know.

**Comment by ssunday** [comment]
It's a low-key problem with this gem is that it's providing all sorts of functionality even if you don't want it. Like it's pulling in aws gems that you may not need.

**Comment by mullermp** [comment]
We made the decision a few years ago to bundle all the features because it's 1) easier for us to manage (develop/release) and 2) more "all in one" and "works out of the box" like rails is itself.

I think we want to keep this pattern but I agree we can probably not bring in SDK gems as dependencies but rather check if they are loaded and enable those features as such.

File: lib/aws/rails/action_mailbox/engine.rb [hunk 1]
```diff
@@ -1,14 +1,14 @@
...
       # @api private
       class Engine < ::Rails::Engine
-        config.action_mailbox.ses = ActiveSupport::OrderedOptions.new
-        config.action_mailbox.ses.s3_client_options ||= {}
+        if config.respond_to?(:action_mailbox)
+          config.action_mailbox.ses = ActiveSupport::OrderedOptions.new
+          config.action_mailbox.ses.s3_client_options ||= {}
+        end
 
         initializer 'aws-sdk-rails.mount_engine' do |app|
```
Comment (alextwoods) [inline lib/aws/rails/action_mailbox/engine.rb:13]: Should this also be inside the if block?

File: lib/aws/rails/action_mailbox/engine.rb [hunk 2]
```diff
@@ -1,14 +1,14 @@
...
-require 'action_mailbox/engine'
-
 module Aws
   module Rails
     module ActionMailbox
       # @api private
       class Engine < ::Rails::Engine
-        config.action_mailbox.ses = ActiveSupport::OrderedOptions.new
-        config.action_mailbox.ses.s3_client_options ||= {}
+        if config.respond_to?(:action_mailbox)
```
Comment (alextwoods) [inline lib/aws/rails/action_mailbox/engine.rb:8]: Should we also check that ActionMailbox is loaded? (ie, check if the module `ActionMailbox` is defined?)

Comment (mullermp) [reply lib/aws/rails/action_mailbox/engine.rb:8]: ActionMailbox can be loaded (i.e. `require 'action_mailbox'`) but this can still fail, it really needs `action_mailbox/engine`.

File: lib/aws/rails/action_mailbox/engine.rb (hunk 1 above)
Comment (mullermp) [reply lib/aws/rails/action_mailbox/engine.rb:13]: I guess it could be. But I think there's a larger problem about where this actually belongs

**Review by alextwoods — APPROVED** [review]
